<?php
$aLang = array(
    'charset'                      => 'UTF-8',
    'gn2_newsletterconnect_config' => "NewsletterConnect",

    'GN2_NEWSLETTERCONNECT_MAIN'   => 'Allgemein',
    'GN2_NEWSLETTERCONNECT_API_BASEURL' => 'Mailingwork API-Base-URL',
    'GN2_NEWSLETTERCONNECT_API_USERNAME' => 'Benutzername',
    'GN2_NEWSLETTERCONNECT_API_PASSWORD' => 'Passwort',
    'GN2_NEWSLETTERCONNECT_API_SIGNUPSETUP_GENERAL' => 'ID des Hauptanmeldesetups',
    'GN2_NEWSLETTERCONNECT_API_SIGNOFFSETUP_GENERAL' => 'ID des Hauptabmeldesetups',
    'GN2_NEWSLETTERCONNECT_API_SIGNUPSETUP_ACCOUNT' => 'ID des Anmeldesetups (Kundenaccount)',
    'GN2_NEWSLETTERCONNECT_API_SIGNOFFSETUP_ACCOUNT' => 'ID des Abmeldesetups (Kundenaccount)',
    'GN2_NEWSLETTERCONNECT_API_CONFIG'     => 'API-Konfiguration',
    'GN2_NEWSLETTERCONNECT_API_IPS'   => 'IP-Adressen, die die Gutschein/Profilmanager-APIs aufrufen d&uuml;rfen: <span>(eine pro Zeile)</span>',
    'GN2_NEWSLETTERCONNECT_VOUCHERSERIES'=> 'Gutscheinserie:',
    'GN2_NEWSLETTERCONNECT_YOURIP' => 'Ihre IP-Adresse: ',

    //export subscribers
    'GN2_NEWSLETTERCONNECT_EXPORT_BUTTON'      => 'Export Kundendaten',
    'GN2_NEWSLETTERCONNECT_EXPORT_BUTTON_TITLE'=> 'Abonnenten werden direkt zur Mailing-Works Abonnentenliste eingetragen.',
    'GN2_NEWSLETTERCONNECT_EXPORT_HEADER'       => 'Export Kundendaten',
    'GN2_NEWSLETTERCONNECT_EXPORT_TITLE'        => 'Exportieren Sie die OXID Newsletter-Abonnenten zur Mailing-Works.',
    'GN2_NEWSLETTERCONNECT_TOTAL_SUBSCRIBERS'   => 'Gesamtzahl der Kundendaten',
    'GN2_NEWSLETTERCONNECT_OPTIN_SUBSCRIBERS'   => 'Kunden mit best&auml;tigtem Abonnement',
    'GN2_NEWSLETTERCONNECT_UNCONFIRMED_SUBSCRIBERS' => 'Kunden mit unbest&auml;tigtem Abonnement',
    'GN2_NEWSLETTERCONNECT_OPTOUT_SUBSCRIBERS'  => 'Kunden mit abgemeldetem Abonnement',
    'GN2_NEWSLETTERCONNECT_NOT_SUBSCRIBERS'  => 'Kunden ohne Abonnement',
    'GN2_NEWSLETTERCONNECT_CHECKBOX_TITLE'     => 'zum Export hinzufügen',
    'GN2_NEWSLETTERCONNECT_LISTID'              => 'Abonnenten List-ID',
    'GN2_NEWSLETTERCONNECT_MODE_ADD_LABEL'            => 'Hinzuf&uuml;gen',
    'GN2_NEWSLETTERCONNECT_MODE_ADD_DESC'            => 'Importierte Abonnenten hinzuf&uuml;gen, auch bereits vorhandene (Dubletten).</br>(Abonnenten-IDs neu anlegen)',
    'GN2_NEWSLETTERCONNECT_MODE_REPLACE_LABEL'            => 'Ersetzen',
    'GN2_NEWSLETTERCONNECT_MODE_REPLACE_DESC'         => 'Liste leeren und durch importierte Abonnenten ersetzen.</br>(Abonnenten-IDs neu anlegen)',
    'GN2_NEWSLETTERCONNECT_MODE_UPDATE_LABEL'         => 'Aktualisieren',
    'GN2_NEWSLETTERCONNECT_MODE_UPDATE_DESC'            => 'Vorhandene Abonnenten aktualisieren, keine neuen hinzuf&uuml;gen.</br>(Abonnenten-IDs erhalten)',
    'GN2_NEWSLETTERCONNECT_MODE_UPDATE_ADD_LABEL'       => 'Aktualisieren und hinzuf&uuml;gen (empfohlen)',
    'GN2_NEWSLETTERCONNECT_MODE_UPDATE_ADD_DESC'        => 'Vorhandene Abonnenten aktualisieren und neue hinzuf&uuml;gen.</br>(Abonnenten-IDs erhalten)',
    'GN2_NEWSLETTERCONNECT_IMPORTART_LEGEND'            => 'Importart ausw&auml;hlen',
    'GN2_NEWSLETTERCONNECT_EXPORT_OXID_STATUS'          => 'Abonnement-Status exportieren',
    'GN2_NEWSLETTERCONNECT_OXID_STATUS_TITLE'          => 'Das Status zu jedem Benutzer wird exportiert. Dafür muss aber das entsprechende Abonnentenfeld -Anmeldestatus- in Mailworks vorhanden sein. ',
);